inst1 = n3m10A.txt
inst2 = n3m10B.txt
inst3 = n3m10C.txt
inst4 = n3m10D.txt
inst5 = n3m10E.txt
inst6 = n3m20A.txt
inst7 = n3m20B.txt
inst8 = n3m20C.txt
inst9 = n3m20D.txt
inst10 = n3m20E.txt
inst11 = n3m40A.txt
inst12 = n3m40B.txt
inst13 = n3m40C.txt
inst14 = n3m40D.txt
inst15 = n3m40E.txt
inst16 = n5m50A.txt
inst17 = n5m50B.txt
inst18 = n5m50C.txt
inst19 = n5m50D.txt
inst20 = n5m50E.txt



all:  Flight
	@echo Compilando...

	@g++ *.cc -o main

clean:
	@echo Limpando Arquivos Objeto e Executavel...
	@rm *.o main

instancia1:
	@echo Executando a Instancia 1...
	@./main $(inst1)

instancia2:
	@echo Executando a Instancia 2...
	@./main $(inst2)

instancia3:
	@echo Executando a Instancia 3...
	@./main $(inst3)

instancia4:
	@echo Executando a Instancia 4...
	@./main $(inst4)